apiVersion: v1
kind: Pod
metadata:
  name: demo-config-volume
spec:
  containers:
  - name: demo-cont
    image: alpine:latest
    command: ["sleep", "9999"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: trading-strategy
  restartPolicy: Never
