apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-app-alpine
  labels:
    app: deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      labels:
        app: deploy-app
    spec:
      containers:
      - name: deploy-app
        image: alpine:latest
        command: ["sleep", "9999"]
        envFrom:
        - configMapRef:
            name: ui-config

