apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: alpine:latest
      command: ["sleep", "9999"]
      env:
        - name: SQLDATABASE_URI
          valueFrom:
            secretKeyRef:
              name: myflaskapp-secret
              key: SQLDATABASE_URI
  restartPolicy: Never
