apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp-httpd
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
i
