apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myflaskapp-deployment
  labels:
    app: myflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: umak/myflaskapp:latest
        ports:
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: myflaskapp-config

