apiVersion: v1
kind: ReplicationController
metadata:
  name: repliction-app-cont
spec:
  replicas: 3
  selector:
    app: replication-app
  template:
    metadata:
      name: repliction-app
      labels:
        app: replication-app
    spec:
      containers:
      - name: replication-app-container
        image: alpine:latest
        command: ["sleep", "9999"]
        envFrom:
        - configMapRef:
            name: ui-config

